[package]
name = "rust-belt"
version = "1.0.0"
authors = [
    "johnthagen <johnthagen@gmail.com>",
    "theandrewdavis <theandrewdavis@gmail.com>",
    "mcdenhoed <mcdenhoed@gmail.com>",
]

[dependencies]
piston = "0.32.0"
piston2d-graphics = "0.21.1"
piston2d-opengl_graphics = "0.43.0"
pistoncore-glutin_window = "0.37.0"
piston-music = "0.19.0"
rand = "0.3.15"