[package]
name = "rust-belt"
version = "0.5.0"
authors = [
    "johnthagen <johnthagen@gmail.com>",
    "theandrewdavis <theandrewdavis@gmail.com>",
    "mcdenhoed <mcdenhoed@gmail.com>",
]

[dependencies]
piston_window = "0.64.0"
piston2d-opengl_graphics = "0.42.0"
piston-music = "0.19.0"